## Importación de librerías

In [14]:
#Tratamiento de datos
import pandas as pd

#Visualizaciones
import matplotlib.pyplot as plt
import seaborn as sns

#Configuración ruta
import sys
sys.path.append('../')

from src.soporte import analisis_rapido

## Carga de datos

In [15]:
data = pd.read_csv('../data/output/autorenew_limpio.csv')

In [16]:
data.head()

,name,price,vehicleType,yearOfRegistration,gearbox,powerCV,kilometer,fuelType,brand,notRepairedDamage
0,Golf_3_1.6,480,unknown,1993,manually,NaN,150000,petrol,volkswagen,unknown
1,A5_Sportback_2.7_Tdi,18300,coupe,2011,manually,187.0,125000,diesel,audi,yes
2,"Jeep_Grand_Cherokee_""Overland""",9800,suv,2004,automatic,161.0,125000,diesel,jeep,unknown
3,GOLF_4_1_4__3TÜRER,1500,small car,2001,manually,74.0,150000,petrol,volkswagen,no
4,Skoda_Fabia_1.4_TDI_PD_Classic,3600,small car,2008,manually,68.0,90000,diesel,skoda,no

## Objetivo del análisis

- Averiguar qué marcas son las mas vendidas, el rango de precios correspondiente y la antiguedad de los vehículos.
- Para evitar que vehiculos que tengan danos puedan sesgar el conjunto de datos y las conclusiones que saquemos, nos centraremos en el subconjunto de datos de vehiculos sin danos.

In [17]:
data['notRepairedDamage'].value_counts()

notRepairedDamage
no         258961
unknown     64571
yes         33291
Name: count, dtype: int64

In [18]:
df = data[data['notRepairedDamage'] == 'no'].copy()

Me quedo sólo con los que no tienen daños, entonces elimino columna.

In [19]:
df.drop(columns=['notRepairedDamage'], inplace=True)

## Análisis

In [20]:
df.head()

,name,price,vehicleType,yearOfRegistration,gearbox,powerCV,kilometer,fuelType,brand
3,GOLF_4_1_4__3TÜRER,1500,small car,2001,manually,74.0,150000,petrol,volkswagen
4,Skoda_Fabia_1.4_TDI_PD_Classic,3600,small car,2008,manually,68.0,90000,diesel,skoda
6,Peugeot_206_CC_110_Platinum,2200,convertible,2004,manually,108.0,150000,petrol,peugeot
9,Mazda_3_1.6_Sport,2000,unknown,2004,manually,104.0,150000,petrol,mazda
12,VW_PASSAT_1.9_TDI_131_PS_LEDER,2500,combi,2004,manually,129.0,150000,unknown,volkswagen

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 258961 entries, 3 to 356822
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   name                258961 non-null  object
 1   price               258961 non-null  int64
 2   vehicleType         258961 non-null  object
 3   yearOfRegistration  258961 non-null  int64
 4   gearbox             258961 non-null  object
 5   powerCV             244341 non-null  float64
 6   kilometer           258961 non-null  int64
 7   fuelType            258961 non-null  object
 8   brand               258961 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 19.8+ MB

In [22]:
df.duplicated().sum()

8610

In [23]:
df.isna().mean().round(4) * 100

name                  0.00
price                 0.00
vehicleType           0.00
yearOfRegistration    0.00
gearbox               0.00
powerCV               5.65
kilometer             0.00
fuelType              0.00
brand                 0.00
dtype: float64

## Análisis

In [ ]:
''' //Exportacion a SRC, ejecuto analisis_rapido al cominezo y lo borro//

    """
    Función que proporciona un análisis rápido de un DataFrame.
    Parámetros:
    df: DataFrame a analizar.
    n: Número de filas (por defecto = 5)
    
    """

    print(f"Las {n} primeras columnas son:")
    display(df.head(n))
    print("Información básica del DataFrame:")
    display(df.info())
  
    print(f"El número de duplicados es: {df.duplicated().sum()}")
    display(df.isna().mean().round(4) * 100)//

def analisis_rapido(df, n=5):

    """
    Función que proporciona un análisis rápido de un DataFrame.
    Parámetros:
    df: DataFrame a analizar.
    n: Número de filas (por defecto = 5)
    
    """

    print(f"Las {n} primeras columnas son:")
    display(df.head(n))
    print("Información básica del DataFrame:")
    display(df.info())
  
    print(f"El número de duplicados es: {df.duplicated().sum()}")
    display(df.isna().mean().round(4) * 100)
'''

' Exportacion a SRC//\n\ndef analisis_rapido(df, n=5):\n\n    """\n    Función que proporciona un análisis rápido de un DataFrame.\n    Parámetros:\n    df: DataFrame a analizar.\n    n: Número de filas (por defecto = 5)\n    \n    """\n\n    print(f"Las {n} primeras columnas son:")\n    display(df.head(n))\n    print("Información básica del DataFrame:")\n    display(df.info())\n  \n    print(f"El número de duplicados es: {df.duplicated().sum()}")\n    display(df.isna().mean().round(4) * 100)\n'

In [25]:
analisis_rapido(df, 3)

Las 3 primeras columnas son:

,name,price,vehicleType,yearOfRegistration,gearbox,powerCV,kilometer,fuelType,brand
3,GOLF_4_1_4__3TÜRER,1500,small car,2001,manually,74.0,150000,petrol,volkswagen
4,Skoda_Fabia_1.4_TDI_PD_Classic,3600,small car,2008,manually,68.0,90000,diesel,skoda
6,Peugeot_206_CC_110_Platinum,2200,convertible,2004,manually,108.0,150000,petrol,peugeot

Información básica del DataFrame:
<class 'pandas.core.frame.DataFrame'>
Index: 258961 entries, 3 to 356822
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   name                258961 non-null  object
 1   price               258961 non-null  int64
 2   vehicleType         258961 non-null  object
 3   yearOfRegistration  258961 non-null  int64
 4   gearbox             258961 non-null  object
 5   powerCV             244341 non-null  float64
 6   kilometer           258961 non-null  int64
 7   fuelType            258961 non-null  object
 8   brand               258961 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 19.8+ MB

None

El número de duplicados es: 8610

name                  0.00
price                 0.00
vehicleType           0.00
yearOfRegistration    0.00
gearbox               0.00
powerCV               5.65
kilometer             0.00
fuelType              0.00
brand                 0.00
dtype: float64

Como hay pocos nulos en `powerCV` los elimino

In [26]:
#eliminamos filas con valores nulos, ya que no son muchas y no queremos perder información de otras columnas.
df.dropna(inplace=True)

In [28]:
df.columns

Index(['name', 'price', 'vehicleType', 'yearOfRegistration', 'gearbox',
       'powerCV', 'kilometer', 'fuelType', 'brand'],
      dtype='object')

## Columnas del dataset Limpio

- `name` : Nombre del anuncio, normalmente incluye la marca y el modelo del coche.
- `price` : Precio del coche en la moneda local (probablemente euros o dolares).
- `vehicleType` : Tipo de vehículo (sedán, SUV, compacto, etc.).
- `yearOfRegistration` : Año en el que se matriculo el coche.
- `gearbox` : Tipo de transmision (manual o automatica).
- `powerCV` : Potencia del coche en caballos de vapor (CV).
- `kilometer` : Kilometraje total del coche.
- `fuelType` : Tipo de combustible (gasolina, diésel, eléctrico, etc.).
- `brand` : Marca del coche.

17.27